config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:6, maximum:100}
  validates :description, presence: true, length: {minimum:10, maximum:300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum:3, maximum:25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum:105 }, 
  format: {with: VALID_EMAIL_REGEX}
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  
  def show 
  end
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    @article = Article.new(articel_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def  update
    if @article.update(articel_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def articel_params
    params.require(:article).permit(:title, :description)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end
  
  def index
    @users = User.all
  end
  
  def new
    @user =User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:notice] = "Welcome to the Alpha Academy"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.user.username %></td>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %> </td>
        <td><%= link_to 'Edit', edit_article_path(article) %> </td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %> </td>
      </tr> 
    <% end %> 
  </tbody>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local:true) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to  "Cancel and return to articles listing", articles_path %>

app/views/articles/index.html.erb
<h1>Index</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan='3'>Actions</th>
    </tr>
  </thead>
  
  
  <%= render 'article' %> 
  
</table>
<br>
<%= link_to  "Create new article", new_article_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to  "Return to articles listing", articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Author: </strong><%= @article.user.username %></p>
    
<p><strong>Title:</strong> <%= @article.title %> </p>
<p><strong>Description: </strong> <%= @article.description %> </p>

<%= link_to  "Edit", edit_article_path(@article) %> |
<%= link_to  "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to  "Return to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to  "Articles listing", articles_path %> |
<%= link_to  "Home page", root_path %>

app/views/pages/home.html.erb
<h1>Yolo World!</h1>

<%= link_to  "Articles listing", articles_path %> |
<%= link_to  "About page", about_path %>
<%= link_to  "Sign up", signup_path %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local:true) do |f| %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
  
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<%= link_to  "Return to articles listing", articles_path %>

app/views/users/index.html.erb
<h1>Alpha bloggers</h1>

<tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= pluralize(user.articles.count, "article") %></td>
        <td><%= link_to 'View profile', user %> </td>
        <td><%= link_to 'Edit profile', edit_user_path(user) %> </td>
      </tr> 
    <% end %> 
  </tbody>
<%= link_to  "Return to articles listing", articles_path %>

app/views/users/new.html.erb
<h1>Sign up for alpha blog</h1>

<%= render 'form' %>

<%= link_to  "Return to articles listing", articles_path %>

app/views/users/show.html.erb
<h1> <%= @user.username%>'s Profile</h1>
<h3>Articles</h3>

<%= link_to  "edit your profile", edit_user_path(@user) %>

<%= render 'articles/article' %>

<%= link_to  "Return to articles listing", articles_path %>